# Introduction to Python
## Python Basics

In [1]:
# Question 0:
# import pandas as pd and numpy as np.
import pandas as pd
import numpy as np

In [2]:
# Question 1:
# Write a NumPy program to test whether none of the elements of a given array is zero. 
# Hint: google for np.all
np.all([1, 2, 3, 1])

True

In [3]:
# Question 2:
# Write a NumPy program to test if any of the elements of a given array is non-zero. 
# Hint: google for similar function to np.all
np.any([0, 1, 0, 0])

True

In [4]:
# Question 3:
# Write a NumPy program to test element-wise for NaN of a given array.
a = np.array([1, 0, np.nan, -np.inf, np.inf])
print(np.isnan(a))

[False False  True False False]


In [5]:
# Question 4:
# Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.
np.append(np.zeros(10), np.ones(10) * 5)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [6]:
# Question 5:
# Write a NumPy program to create an array of the integers from 30 to 70.
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [8]:
# Question 6:
# Write a NumPy program to create an array of all the even integers from 30 to 70.
list(filter(lambda x : x % 2 == 0, np.arange(30,71)))

[30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70]

In [9]:
# Question 7:
# Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values 
# except the first and last.
np.arange(15, 56)[1:-2]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

In [10]:
# Question 8:
# Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers 
# in the range from 9 to 15

list(map(lambda x: -x if(x > 9 and x < 16) else x ,np.arange(0, 20)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, -10, -11, -12, -13, -14, -15, 16, 17, 18, 19]

In [11]:
# Question 9:
# Python program to check whether the given number is even or not. The function should return True 
# for an even number and false for an odd number.

def even_number(x):
    if x % 2 == 0:
        return True
    else:
        return False
    
assert even_number(3) == False
assert even_number(5) == False
assert even_number(10) == True

In [12]:
# Question 10:
# Write a function that take a 2D points and a list of 2 points (in an 2D numpy array format) 
# and return the index of the closest point in the list (according to euclidian distance)
import math

def get_closest(point, points):
    
    minimum_index = np.inf
    minimum_distance = np.inf
    
    for index, single_point in enumerate(points):
        left = (point[0] - single_point[0]) ** 2
        right = (point[1] - single_point[1]) ** 2
        distance = math.sqrt(left + right)
        
        if distance < minimum_distance:
            minimum_distance = distance
            minimum_index = index
            
    return minimum_index
            
assert get_closest(np.array([0.1, 0.5]), np.array([[0.2, 0.4],[0.1, 0.2],[0.5, 0.0]])) == 0
assert get_closest(np.array([5.1, 4.3]), np.array([[0.2, 0.4],[6.1, 4.2],[0.5, 0.0]])) == 1
assert get_closest(np.array([3.1, 2.0]), np.array([[0.2, 0.4],[6.1, 4.2],[3.0, 2.0]])) == 2

In [13]:
# Question 11:
# Write a function that does the min-max scale the values of an array between 0 and 1.

def scale(array):
    return (array - min(array)) / max(array) - min(array)

In [14]:
# Question 12:
# What does the following return?

[1, 2] + [1, 2]

[1, 2, 1, 2]

In [15]:
# Question 13:
# Write a function that return the third greatest element

def get_third_greatest(x):
    x.sort()
    return x[-3]
    
assert get_third_greatest([82, 57, 65, 81, 99, 85, 98, 91, 33, 48])  == 91
assert get_third_greatest([-1, 42, -25, 38, -12])  == -1

In [16]:
# Question 14:
# Select all elements greater than 10 and smaller than 70

def select(x):
    return [el for el in x if (el > 10 and el < 70)]

assert select([82, 57, 65, 81, 99, 85, 98, 91, 33, 48]) == [57, 65, 33, 48]

## Python for Data Science

In [15]:
import pandas as pd

# Dataframe to work with
df = pd.DataFrame(data = [[3, 7, 'Friday', 'Mary'],
                          [2, 2, 'Tuesday', 'Mary'],
                          [6, 4, 'Friday', 'Mary'],
                          [3, 5, 'Tuesday', 'Mary'],
                          [1, 2, 'Friday', 'Mary'],
                          [9, 5, 'Friday', 'Mary'],
                          [3, 1, 'Friday', 'John'],
                          [9, 6, 'Tuesday', 'John'],
                          [4, 2, 'Monday', 'Mary'],
                          [1, 8, 'Friday', 'John']], 
                  columns = ['price_per_unit', 'nb_units', 'day', 'players'])

In [16]:
# Question 15:
# How much money did John spend?
df["total"] = df["price_per_unit"] * df["nb_units"]
df[df['players'] == 'John']['total'].sum()

65

In [17]:
# Question 16:
# How much money did each player spend each day?
df.groupby("players")["total"].sum()

players
John     65
Mary    119
Name: total, dtype: int64

In [17]:
# Question 17:
# Create a dataframe, with following output:

# output:
#        name  score  attempts qualify
#0  Anastasia   12.5         1     yes
#1       Dima    9.0         3      no
#2  Katherine   16.5         2     yes
#3      James    NaN         3      no
#4      Emily    9.0         2      no

name = ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily']
score = [12.5, 9.0, 16.5, np.nan, 9.0]
attempts = [1, 3, 2, 3, 2]
qualify = ["yes", "no", "yes", "no", "no"]

df = {"name" : name,
     "score" : score,
     "attempts" : attempts,
     "qualify" : qualify}

student = pd.DataFrame(df)

In [24]:
# Question 18:
# create a new dataframe, student, that uses the labels below as index ('name' of each row)
labels = ['a', 'b', 'c', 'd', 'e']
student.index = labels

# desired output:
#   attempts       name qualify  score                                  
#a         1  Anastasia     yes   12.5                                  
#b         3       Dima      no    9.0                                  
#c         2  Katherine     yes   16.5                                  
#d         3      James      no    NaN                                  
#e         2      Emily      no    9.0    

In [26]:
# Question 19:
# Fill the empty null values of the score column with 0
student['score'].replace({np.nan : 0}, inplace = True)

In [27]:
# Question 20:
# Write a Pandas program to change the score in row 'd' to 11.5
student.loc["d", "score"] = 11.5

In [30]:
# Question 21:
# Write a Pandas program to calculate the sum of the examination attempts by all students. (like with numpy)
student.groupby("name")["attempts"].sum()

name
Anastasia    1
Dima         3
Emily        2
James        3
Katherine    2
Name: attempts, dtype: int64

In [29]:
# Question 22:
# Write a Pandas program to calculate the mean score in the student DataFrame
student.score.mean()

11.7

In [31]:
# Question 23:
# Write a Pandas program to sort the data frame first by 'name' in descending order
student.sort_values("name", ascending = False)

name  score  attempts qualify
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

In [ ]:
# Question 24:
# Write a Pandas program to get the columns and shape of the student DataFrame
